### ISSUE TITLE
WebDriverException when run with auth.display=true option

### ISSUE THREAD

**Issue by MaciejBala** [ICTU/zap-baseline#36]
Hi, I'm trying to run scan with authentication and I was trying this one option, then I got the following error:

`2021-08-11 13:07:03,583 Start webdriver
Traceback (most recent call last):
  File "/zap/zap_auth.py", line 88, in authenticate
    self.setup_webdriver()
  File "/zap/zap_auth.py", line 67, in setup_webdriver
    self.driver = webdriver.Firefox(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
2021-08-11 13:07:03,696 error in authenticate: None`

running on Windows PowerShell. It does depend on that option, when I set false it runs as intended.
If there's any other way to contact you guys (Slack/Team Speak) I would gladly do so. Thanks a lot

**Comment by MaciejBala** [comment]
Is it because I'm trying to run it non-headless on docker?

**Comment by dicksnel** [comment]
Hi, yes I think it is because you are running with display on inside Docker. I don't know if this is possible. If you run it without Docker it should work.

**Comment by MaciejBala** [comment]
That's too bad :/ We're using json based authentication w/Keycloak and running it with selenium seems to be the only way to collect all the tokens needed. Couldn't do it with OWASP automation framework. 
Anyway, thanks for clarifying that. I'll close the ticket now.
Keep up the good work

**Comment by dicksnel** [comment]
@MaciejBala why do you need to display the browser? It is only for debugging purposes. Everything should work in headless mode.
