### ISSUE TITLE
DEBUG:root:zap open error

### ISSUE THREAD

**Issue by anshul1107** [ICTU/zap-baseline#6]
Getting below error while running zap baseline custom py from docker container for active scan.

DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:root:zap open error
DEBUG:root:Setup a new context
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
WARNING:root:I/O error: HTTPConnectionPool(host='localhost', port=58326): Max retries exceeded with url: http://zap/JSON/context/action/newContext/?apikey=&contextName=auth (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f775ceec6d0>: Failed to establish a new connection: [Errno 111] Connection refused',)))
Traceback (most recent call last):
  File "/zap/zap-baseline-custom.py", line 401, in main
    contextId = zap.context.new_context('auth')
  File "/usr/local/lib/python2.7/dist-packages/zapv2/context.py", line 90, in new_context
    return six.next(six.itervalues(self.zap._request(self.zap.base + 'context/action/newContext/', {'contextName': contextname, 'apikey': apikey})))
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 159, in _request
    data = self._request_api(url, get)
  File "/usr/local/lib/python2.7/dist-packages/zapv2/__init__.py", line 149, in _request_api
    return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 485, in send
    raise ProxyError(e, request=request)
ProxyError: HTTPConnectionPool(host='localhost', port=58326): Max retries exceeded with url: http://zap/JSON/context/action/newContext/?apikey=&contextName=auth (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f775ceec6d0>: Failed to establish a new connection: [Errno 111] Connection refused',)))

**Comment by anshul1107** [comment]
Getting below while running zap baseline custom docker container for active scan


DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
DEBUG:root:zap open error
DEBUG:root:Setup a new context
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
WARNING:root:I/O error: HTTPConnectionPool(host='localhost', port=58326): Max retries exceeded with url: http://zap/JSON/context/action/newContext/?apikey=&contextName=auth (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f775ceec6d0>: Failed to establish a new connection: [Errno 111] Connection refused',)))
Traceback (most recent call last):
File "/zap/zap-baseline-custom.py", line 401, in main
contextId = zap.context.new_context('auth')
File "/usr/local/lib/python2.7/dist-packages/zapv2/context.py", line 90, in new_context
return six.next(six.itervalues(self.zap._request(self.zap.base + 'context/action/newContext/', {'contextName': contextname, 'apikey': apikey})))
File "/usr/local/lib/python2.7/dist-packages/zapv2/init.py", line 159, in _request
data = self._request_api(url, get)
File "/usr/local/lib/python2.7/dist-packages/zapv2/init.py", line 149, in _request_api
return self.session.get(url, params=query, proxies=self.__proxies, verify=False)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
return self.request('GET', url, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 485, in send
raise ProxyError(e, request=request)
ProxyError: HTTPConnectionPool(host='localhost', port=58326): Max retries exceeded with url: http://zap/JSON/context/action/newContext/?apikey=&contextName=auth (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f775ceec6d0>: Failed to establish a new connection: [Errno 111] Connection refused',)))

**Comment by dicksnel** [comment]
If this is still relevant, please reopen the issue.
